//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPRssReader.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPRssReader.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string add_cancel {
            get {
                return ResourceManager.GetString("add_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add feed.
        /// </summary>
        public static string add_feed {
            get {
                return ResourceManager.GetString("add_feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, input RSS link, like: http://example.com/
        ///or copy/paste from browser.
        /// </summary>
        public static string add_feed_instruction {
            get {
                return ResourceManager.GetString("add_feed_instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New feed added.
        /// </summary>
        public static string add_message {
            get {
                return ResourceManager.GetString("add_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid addres :(.
        /// </summary>
        public static string add_message_error {
            get {
                return ResourceManager.GetString("add_message_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string add_save {
            get {
                return ResourceManager.GetString("add_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string add_search {
            get {
                return ResourceManager.GetString("add_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add star.
        /// </summary>
        public static string add_star {
            get {
                return ResourceManager.GetString("add_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All read.
        /// </summary>
        public static string check_all {
            get {
                return ResourceManager.GetString("check_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas and recomendations you can send to eguurt@gmail.com . I glad to read some news :).
        /// </summary>
        public static string contact_me {
            get {
                return ResourceManager.GetString("contact_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © Yahor Malkevich 2012.
        /// </summary>
        public static string copyright {
            get {
                return ResourceManager.GetString("copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, can not update....
        /// </summary>
        public static string date_fail {
            get {
                return ResourceManager.GetString("date_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update at {0}.
        /// </summary>
        public static string date_last_update {
            get {
                return ResourceManager.GetString("date_last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating... Please wait..
        /// </summary>
        public static string date_updating {
            get {
                return ResourceManager.GetString("date_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feedback.
        /// </summary>
        public static string feedback {
            get {
                return ResourceManager.GetString("feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave feedback.
        /// </summary>
        public static string leave_feedback {
            get {
                return ResourceManager.GetString("leave_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to load more items....
        /// </summary>
        public static string load_more_items {
            get {
                return ResourceManager.GetString("load_more_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string main_all {
            get {
                return ResourceManager.GetString("main_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string main_delete {
            get {
                return ResourceManager.GetString("main_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feeds.
        /// </summary>
        public static string main_feeds {
            get {
                return ResourceManager.GetString("main_feeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, need some feed for start....
        /// </summary>
        public static string main_feeds_empty {
            get {
                return ResourceManager.GetString("main_feeds_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string main_move_down {
            get {
                return ResourceManager.GetString("main_move_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string main_move_up {
            get {
                return ResourceManager.GetString("main_move_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string main_new {
            get {
                return ResourceManager.GetString("main_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin to start.
        /// </summary>
        public static string main_pint_to_start {
            get {
                return ResourceManager.GetString("main_pint_to_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starred.
        /// </summary>
        public static string main_starred {
            get {
                return ResourceManager.GetString("main_starred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string main_update {
            get {
                return ResourceManager.GetString("main_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data, try refresh....
        /// </summary>
        public static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove star.
        /// </summary>
        public static string remove_star {
            get {
                return ResourceManager.GetString("remove_star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove stars.
        /// </summary>
        public static string remove_stars {
            get {
                return ResourceManager.GetString("remove_stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string setting_about {
            get {
                return ResourceManager.GetString("setting_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading items at a time.
        /// </summary>
        public static string setting_article_on_page {
            get {
                return ResourceManager.GetString("setting_article_on_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update feeds on start.
        /// </summary>
        public static string setting_feed_on_start {
            get {
                return ResourceManager.GetString("setting_feed_on_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string setting_general {
            get {
                return ResourceManager.GetString("setting_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string setting_name {
            get {
                return ResourceManager.GetString("setting_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you read? :).
        /// </summary>
        public static string tile_content {
            get {
                return ResourceManager.GetString("tile_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New articles.
        /// </summary>
        public static string tile_title {
            get {
                return ResourceManager.GetString("tile_title", resourceCulture);
            }
        }
    }
}
